### ISSUE TITLE
Why use NodeJS runtime instead of Amazon Linux 2023?

### ISSUE THREAD

**Issue by ShivamJoker** [tmokmss/cdk-lambda-llrt#1]
Hey Thanks for this library!

In the [LLRT repo](https://github.com/awslabs/llrt/blob/main/README.md#option-1-custom-runtime-recommended)  the first recommendation is on using the AL2023 runtime.
So if we use NODEJS runtime, won't it impact the performance?

**Comment by tmokmss** [comment]
Hi, it's already using AL2023. We override the runtime here: https://github.com/tmokmss/cdk-lambda-llrt/blob/8de22202cec1343f678b13ab9292abaf543f32e5/src/llrt-function.ts#L74

We inherit `NodejsFunction` just to reuse its bundling logic.

**Comment by ShivamJoker** [comment]
Ohh I missed it.
Thanks for pointing it @tmokmss

**Comment by tmokmss** [comment]
No problem :) Feel free to leave feedback if you find anything using this construct.
