### ISSUE TITLE
Add bundle type options

### ISSUE THREAD

**Issue by ThomasAribart** [tmokmss/cdk-lambda-llrt#8]
Hello and thanks for this awesome lib!

AWS Labs expose binaries with support for all sdks or no sdk: See [release binaries](https://github.com/awslabs/llrt/releases) and the [docs](https://github.com/awslabs/llrt#using-aws-sdk-v3-with-llrt).

Is there a way to use those binaries? Say with a `bundleType: 'full-sdk' | 'no-sdk' | 'standard'` option?

**Comment by tmokmss** [comment]
Cool, let's add the option. We have to also change the [`externalModules` property](https://github.com/tmokmss/cdk-lambda-llrt/blob/b9e41f7ff667a0622e627c7568205f53aa7ec547/src/llrt-function.ts#L55-L77) according to the option.

**Comment by tmokmss** [comment]
@ThomasAribart It's available from 0.0.13. Any feedback is welcome :)

**Comment by ThomasAribart** [comment]
Awesome, thanks 🙌
